"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
)

environ.Env.read_env(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

LEARNLOOT_ENVIRONMENT = env.str(
    "LEARNLOOT_ENVIRONMENT",
    default="development",
).strip().lower()
LEARNLOOT_IS_PRODUCTION = LEARNLOOT_ENVIRONMENT == "production"
LEARNLOOT_LOG_LEVEL = env.str("LEARNLOOT_LOG_LEVEL", default="INFO").strip().upper()

ALLOWED_HOSTS = [
    host.strip()
    for host in env.str("DJANGO_ALLOWED_HOSTS").split(",")
    if host.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    "rest_framework",
    "corsheaders",

    # Project apps
    "providers",
    "courses",
    "pricing",
    "discovery",
    "publishing",
    "tracking",
    "shopping",
    "operations",
    "cms",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}
DATABASES["default"]["CONN_MAX_AGE"] = env.int(
    "DJANGO_DB_CONN_MAX_AGE",
    default=60 if LEARNLOOT_IS_PRODUCTION else 0,
)
DATABASES["default"]["CONN_HEALTH_CHECKS"] = LEARNLOOT_IS_PRODUCTION


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = Path(
    env.str(
        "LEARNLOOT_STATIC_ROOT",
        default=str(BASE_DIR / "staticfiles"),
    )
)
MEDIA_URL = env.str("LEARNLOOT_MEDIA_URL", default="/media/").strip() or "/media/"
_media_root = env.str("LEARNLOOT_MEDIA_ROOT", default="").strip()
LEARNLOOT_MEDIA_ROOT_CONFIGURED = bool(_media_root)
MEDIA_ROOT = Path(_media_root) if _media_root else BASE_DIR / "media"
LEARNLOOT_MEDIA_PERSISTENCE_CONFIRMED = env.bool(
    "LEARNLOOT_MEDIA_PERSISTENCE_CONFIRMED",
    default=False,
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in env.str("CORS_ALLOWED_ORIGINS").split(",")
    if origin.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env.str(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        default=env.str("CORS_ALLOWED_ORIGINS", default=""),
    ).split(",")
    if origin.strip()
]

SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=LEARNLOOT_IS_PRODUCTION,
)
CSRF_COOKIE_SECURE = env.bool(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=LEARNLOOT_IS_PRODUCTION,
)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
)
SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

if env.bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

_cache_url = env.str("LEARNLOOT_CACHE_URL", default="").strip()
if _cache_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _cache_url,
            "KEY_PREFIX": "learnloot",
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "learnloot-development",
            "KEY_PREFIX": "learnloot",
            "TIMEOUT": 300,
        }
    }

CELERY_BROKER_URL = env.str("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND")

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

LEARNLOOT_AUTOMATION_ENABLED = env.bool(
    "LEARNLOOT_AUTOMATION_ENABLED",
    default=False,
)
LEARNLOOT_DISCOVERY_INTERVAL_MINUTES = max(
    env.int("LEARNLOOT_DISCOVERY_INTERVAL_MINUTES", default=60),
    1,
)
LEARNLOOT_DISCOVERY_RUNNING_STALE_MINUTES = max(
    env.int("LEARNLOOT_DISCOVERY_RUNNING_STALE_MINUTES", default=90),
    1,
)
LEARNLOOT_TELEGRAM_MAINTENANCE_INTERVAL_MINUTES = max(
    env.int("LEARNLOOT_TELEGRAM_MAINTENANCE_INTERVAL_MINUTES", default=5),
    1,
)

def build_celery_beat_schedule(
    *,
    enabled: bool,
    discovery_interval_minutes: int,
    telegram_interval_minutes: int,
) -> dict:
    if not enabled:
        return {}

    return {
        "learnloot-discovery-scheduler": {
            "task": "discovery.schedule_active_provider_discovery",
            "schedule": discovery_interval_minutes * 60.0,
        },
        "learnloot-telegram-stale-reconciliation": {
            "task": "publishing.reconcile_stale_telegram_deliveries",
            "schedule": telegram_interval_minutes * 60.0,
        },
        "learnloot-telegram-queue-dispatch": {
            "task": "publishing.dispatch_queued_telegram_publications",
            "schedule": telegram_interval_minutes * 60.0,
        },
    }


CELERY_BEAT_SCHEDULE = build_celery_beat_schedule(
    enabled=LEARNLOOT_AUTOMATION_ENABLED,
    discovery_interval_minutes=LEARNLOOT_DISCOVERY_INTERVAL_MINUTES,
    telegram_interval_minutes=LEARNLOOT_TELEGRAM_MAINTENANCE_INTERVAL_MINUTES,
)

# Provider discovery runtime configuration. Automated access remains disabled
# until the operator explicitly acknowledges that the configured source may be
# accessed under the provider's current terms and policies.
LEARNLOOT_UDEMY_DISCOVERY_ACCESS_APPROVED = env.bool(
    "LEARNLOOT_UDEMY_DISCOVERY_ACCESS_APPROVED",
    default=False,
)
LEARNLOOT_UDEMY_DISCOVERY_SOURCE_URL = env.str(
    "LEARNLOOT_UDEMY_DISCOVERY_SOURCE_URL",
    default="https://www.udemy.com/courses/free/",
)
LEARNLOOT_UDEMY_DISCOVERY_MAX_PAGES = env.int(
    "LEARNLOOT_UDEMY_DISCOVERY_MAX_PAGES",
    default=10,
)
LEARNLOOT_UDEMY_DISCOVERY_ITEM_LIMIT = env.int(
    "LEARNLOOT_UDEMY_DISCOVERY_ITEM_LIMIT",
    default=0,
)
LEARNLOOT_UDEMY_DISCOVERY_RENDER_WAIT_MS = env.int(
    "LEARNLOOT_UDEMY_DISCOVERY_RENDER_WAIT_MS",
    default=3500,
)

# Deal scoring and publication eligibility. These rules produce queue items only;
# Telegram delivery remains a later phase.
LEARNLOOT_PUBLICATION_MIN_RATING = env.float(
    "LEARNLOOT_PUBLICATION_MIN_RATING",
    default=4.0,
)
LEARNLOOT_PUBLICATION_MIN_REVIEWS = env.int(
    "LEARNLOOT_PUBLICATION_MIN_REVIEWS",
    default=100,
)
LEARNLOOT_PUBLICATION_MIN_SCORE = env.int(
    "LEARNLOOT_PUBLICATION_MIN_SCORE",
    default=70,
)
LEARNLOOT_PUBLICATION_MAX_COURSE_AGE_HOURS = env.int(
    "LEARNLOOT_PUBLICATION_MAX_COURSE_AGE_HOURS",
    default=24,
)
LEARNLOOT_PUBLICATION_COOLDOWN_HOURS = env.int(
    "LEARNLOOT_PUBLICATION_COOLDOWN_HOURS",
    default=168,
)

# Telegram channel publication. The destination is a Telegram channel; a bot
# token is used only as the official Bot API publishing credential. Disabled by
# default so tests, development, migrations, and admin inspection never send
# real channel posts accidentally.
LEARNLOOT_TELEGRAM_ENABLED = env.bool(
    "LEARNLOOT_TELEGRAM_ENABLED",
    default=False,
)
LEARNLOOT_TELEGRAM_BOT_TOKEN = env.str(
    "LEARNLOOT_TELEGRAM_BOT_TOKEN",
    default="",
)
LEARNLOOT_TELEGRAM_CHANNEL_ID = env.str(
    "LEARNLOOT_TELEGRAM_CHANNEL_ID",
    default=env.str("LEARNLOOT_TELEGRAM_CHAT_ID", default=""),
)
LEARNLOOT_TELEGRAM_API_BASE_URL = env.str(
    "LEARNLOOT_TELEGRAM_API_BASE_URL",
    default="https://api.telegram.org",
)
LEARNLOOT_TELEGRAM_TIMEOUT_SECONDS = env.float(
    "LEARNLOOT_TELEGRAM_TIMEOUT_SECONDS",
    default=10.0,
)
LEARNLOOT_TELEGRAM_MAX_RETRIES = env.int(
    "LEARNLOOT_TELEGRAM_MAX_RETRIES",
    default=3,
)
LEARNLOOT_TELEGRAM_RETRY_BASE_SECONDS = env.int(
    "LEARNLOOT_TELEGRAM_RETRY_BASE_SECONDS",
    default=30,
)
LEARNLOOT_TELEGRAM_STALE_SEND_MINUTES = env.int(
    "LEARNLOOT_TELEGRAM_STALE_SEND_MINUTES",
    default=15,
)
LEARNLOOT_PUBLIC_BASE_URL = env.str(
    "LEARNLOOT_PUBLIC_BASE_URL",
    default="http://localhost:3000",
)

# Outbound click analytics. The short dedupe window reduces accidental double
# clicks without storing IP addresses or user-agent strings in the database.
LEARNLOOT_OUTBOUND_CLICK_DEDUPE_SECONDS = env.int(
    "LEARNLOOT_OUTBOUND_CLICK_DEDUPE_SECONDS",
    default=2,
)

# Production-friendly logging defaults to stdout. Hosting/runtime layers remain
# responsible for collection, rotation, retention, and alerting.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "learnloot": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "learnloot",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LEARNLOOT_LOG_LEVEL,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "learnloot": {
            "handlers": ["console"],
            "level": LEARNLOOT_LOG_LEVEL,
            "propagate": False,
        },
    },
}
