import type { Metadata } from "next";
import { PolicyPage } from "@/components/policy-page";

export const metadata: Metadata = { title: "Privacy policy", description: "Learn how LearnLoot handles public requests, privacy-minimized outbound click events, staff sessions, and third-party links.", alternates: { canonical: "/legal/privacy" } };

export default function PrivacyPolicyPage() {
  return <PolicyPage eyebrow="Legal" title="Privacy policy" intro="This policy describes the information LearnLoot intentionally processes in the current application. It is written to match the implemented public and staff workflows rather than a generic analytics template.">
    <h2>1. Public browsing</h2><p>LearnLoot serves public course pages, shopping editorial, policy pages, and redirects to third-party providers and merchants. Standard web infrastructure may process technical request information such as IP address, user agent, timestamps, and requested URLs as necessary to deliver and secure HTTP requests. Hosting or reverse-proxy logging practices may add operational logs outside the application database.</p>
    <h2>2. Privacy-minimized outbound click events</h2><p>When a visitor continues from a LearnLoot course page, the application can store the course, normalized source/campaign attribution, and event time. Shopping redirects can similarly store the product, source/campaign attribution, and event time. The ClickEvent and ShoppingClickEvent database records do not persist raw IP addresses or user-agent strings.</p><p>For a short duplicate-click window, the application may derive an HMAC-based cache key from the request IP address and the destination record. That key is used to reduce accidental duplicate events and is not stored as a raw IP address in the analytics tables.</p>
    <h2>3. Cookies</h2><p>The current public site does not intentionally install advertising or behavioral-analytics cookies. The staff-only administration system uses essential Django session and CSRF cookies for authentication and request protection. If LearnLoot later adds non-essential public analytics or advertising technologies, this policy and any required consent experience should be updated before deployment.</p>
    <h2>4. Staff administration</h2><p>Authorized staff can authenticate to the custom administration area. The system processes account identifiers needed for authentication and returns staff profile details such as username and email to the authenticated admin interface. CMS actions can create and edit course overrides, shopping editorial, categories, and media.</p>
    <h2>5. Third-party destinations</h2><p>Course redirects can send visitors to third-party course providers such as Udemy. Shopping redirects can send visitors to Shopee destinations entered by editors. After leaving LearnLoot, the third party&apos;s own privacy practices apply. Telegram links likewise open an external service governed by its own policies.</p>
    <h2>6. Data retention</h2><p>LearnLoot retains application data according to operational needs and configured database/cache lifecycles. The source code does not currently define a single universal retention period for every analytics, CMS, infrastructure-log, or backup record. Production operators should establish and document retention periods that fit applicable requirements before launch.</p>
    <h2>7. Security</h2><p>LearnLoot uses staff-only session authentication and CSRF protection for custom CMS APIs, validates outbound HTTPS destinations, separates public and administrative routes, and avoids persisting raw IP/user-agent fields in click analytics models. No system can guarantee absolute security.</p>
    <h2>8. Privacy requests</h2><p>For questions about this policy or a privacy request, use the LearnLoot Contact page. The exact rights available to a person can depend on applicable law and the relationship between the person and LearnLoot.</p>
  </PolicyPage>;
}
